### ISSUE TITLE
Unable to find operation source_object

### ISSUE THREAD

**Issue by matheusho** [Stiivi/bubbles#25]
@Stiivi I've been trying do the sql example, but always I run the program show this message: `bubbles.errors.OperationError: Unable to find operation source_object`. My bubbles version is 0.1 and SQLAlchemy 1.0.14.

Can you help me or show me the error code?

I want to use bubbles to migrate a legacy database (mssql) to new database (mysql) at my work company.

``` python
import bubbles


URL = "https://raw.github.com/Stiivi/cubes/master/examples/hello_world/data.csv"

stores = {
    "target": bubbles.open_store("sql", "sqlite:///")
}

p = bubbles.Pipeline(stores=stores)
p.source_object("csv_source", resource=URL, encoding="utf8")
p.retype({"Amount (US$, Millions)": "integer"})

p.create("target", "data")

p.aggregate("Category", "Amount (US$, Millions)")
p.pretty_print()
p.run()
```

Thanks.

**Comment by wpromatt** [comment]
+1
